### ISSUE TITLE
Add creation time and modified time

### ISSUE THREAD

**Issue by stevekinney** [stevekinney/file-bin#5]
As of 0.2.0, File Bin only returns the title and content of the file. We need it to have the creation time and time of last modification as well.

Here is an example:

``` js
fileBin.find('hello.md').then(file => console.log(file));

/*
Output:

{
  id: 'hello.md',
  content: 'lorem ipsum…',
  createdAt: "Mon Feb 22 2016 08:27:19 GMT-0700 (MST)"
  lastModified: "Mon Feb 22 2016 08:27:19 GMT-0700 (MST)"
*/
```

I'm thinking these should be `Date` objects.

**Comment by JessicaG** [comment]
Dibs with Emily and Jill
